### ISSUE TITLE
Disable analytics?

### ISSUE THREAD

**Issue by blopker** [subosito/flutter-action#190]
I wanted to suggest that this action automatically disable Flutter analytics by running `flutter config --no-analytics` after install. Optionally, people could opt in to the analytics through an option in the actions, like `analytics: true`. For security and privacy reasons I think this would be beneficial, especially for those people working on sensitive codebases or running actions on their own internal workers.

Is this something people are interested in?

**Comment by blopker** [comment]
Looks like people are interested. @subosito, would you take a PR?

**Comment by devoncarew** [comment]
I believe that the flutter tool recognizes when it's running on one of the common CI systems and disables analytics automatically.

**Comment by blopker** [comment]
Just what someone who works for Google might say 😄. But seriously, do you have a pointer to the code that does this? On my workflows Flutter displays the analytics notice. I assume this means Flutter is still sending analytics on Github CI at least:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/757503/219903993-eca47a69-e9fe-4eac-8103-581b6ab7a603.png">

**Comment by devoncarew** [comment]
You can trace through the implementation at the flutter/flutter repo in the packages/flutter_tools directory. Here's a good place to start - the code to detect whether it's running on a bot:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/bot_detector.dart#L69

My suspicion is that it shouldn't be printing that message on a CI. I doesn't hurt to invoke `flutter config --no-analytics` on a CI (esp. if it suppresses that long message in the workflow's log output), but I'd be hesitant about adding it because other people looking at the action might think it was necessary and cargo cult it elsewhere.

Probably the best thing to do would be to follow up w/ an issue on flutter/flutter, confirming that analytics aren't sent on a CI, and perhaps suggesting to turn off that message there.

**Comment by blopker** [comment]
Thanks @devoncarew! Although I'm a little unsure how the code actually works, I've been able to trace it as far as https://github.com/flutter/flutter/blob/6205c110d64351610219d48b52a1a1b9e0140dcd/packages/flutter_tools/lib/src/reporting/usage.dart#L160 which seems to create a mock analytics object if a few conditions are met, one of them is `runningOnBot`. I was also able to find a test (https://github.com/flutter/flutter/blob/530324d2320bd13be50e94a3872ed04579978c0d/packages/flutter_tools/test/general.shard/analytics_test.dart#L320) that at least indicates disabling analytics is the intention when running on CI.

Certainly, the opt-out message in CI logs is confusing though. Anyway, my curiosity is satisfied now. I'll close this out and hopefully anyone looking to disable Flutter's analytics in CI will come across this.
